
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: team-a
  namespace: vclusters
spec:
  targetNamespace: team-a
  storageNamespace: team-a
  chart:
    spec:
      chart: vcluster
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: stealthybox-charts
  interval: 1h
  values:
    serviceCIDR: 100.64.0.0/13
    vcluster:
      image: rancher/k3s:v1.22.12-k3s1
